server:
  port: 8201
spring:
  profiles: dev
  application:
    name: microservicecloud-config-client
eurak:
  client:
    service-url:
      defalutZone: http://eurak-dev.com:7001/eurak/
---
server:
  port: 8202
spring:
  profiles: test
  application:
    name: microservicecloud-config-client
eurak:
  client:
    service-url:
      defalutZone: http://eurak-test.com:7001/eurak/
